#ifndef _SPONSORING_H
#define _SPONSORING_H

unsigned char supporters[] = {
    "Alberto Benítez Sánchez\0"
    "Alexander Holland\0"
    "Alister Mills\0"
    "Alvaro Moreno\0"
    "AmiKit\0"
    "andis.retro.corner\0"
    "Andre Wander\0"
    "André Wösten\0"
    "Andres\0"
    "Andrew English\0"
    "Andrew Hutchings\0"
    "Anubis\0"
    "Arkadiusz Kwaśny\0"
    "Arkadiusz Szychowski\0"
    "Arturas Seputis\0"
    "Aurabin\0"
    "Barry Porch\0"
    "Ben Matthew\0"
    "Benedetto Filippo Diana\0"
    "Benedetto Lorello\0"
    "Bertrand\0"
    "Björn Persson\0"
    "Bo Ståle Kopperud\0"
    "Bob Wicksall\0"
    "Brett Armstrong\0"
    "Brian Gosney\0"
    "Brian King\0"
    "Brielle Harrison\0"
    "Capt. LeChuck\0"
    "Carolina Jones\0"
    "Cathal\0"
    "Cédric Billemont\0"
    "Chance Davis\0"
    "Chris Haywood\0"
    "Chris Robinson\0"
    "Christian Johansson\0"
    "Christophe Thibault\0"
    "Christopher Fraser\0"
    "Christopher Tuckwell\0"
    "Claude Schwarz\0"
    "Cloudhunter \0"
    "d-a-n-x\0"
    "Dagon AmigaOS\0"
    "Dana Ross\0"
    "Danial Phillips\0"
    "Daniel Doran\0"
    "Daniel Varga\0"
    "Danilo Savioni\0"
    "Dave Walz aka Kung-Fu\0"
    "David Ferguson\0"
    "David Raulo\0"
    "Davide C\0"
    "dgial\0"
    "Diogo Borges\0"
    "Emiliano Esposito\0"
    "Enrique Mecklenburg Serkovic\0"
    "Enver Paul\0"
    "eXeler0\0"
    "Fabrizio Lodi\0"
    "Fabrizio Radica\0"
    "Fafa\0"
    "Fasih Rehman\0"
    "Federico Stango\0"
    "Ferenc Boldog\0"
    "FishWhistle\0"
    "flype\0"
    "Földesi Péter\0"
    "Frank Eersels\0"
    "Frank Lowe\0"
    "G. Z.\0"
    "Gaetano Giarrusso\0"
    "Geijer\0"
    "George Alibinisis\0"
    "Gerd Kautzmann\0"
    "Giants Christophe\0"
    "Giuseppe De Vincenzi\0"
    "Greg Dyke\0"
    "grovdata\0"
    "Harri Tikkanen\0"
    "Héctor Juan\0"
    "HPh\0"
    "Igor Ianov\0"
    "Ingo Schmitz\0"
    "iMICA Ltd.\0"
    "Ireneusz Bohatyrewicz\0"
    "IridiumFX\0"
    "Jachym Cinematic Studio\0"
    "Jaime Cagigal Bordonaba\0"
    "James Boyd\0"
    "James Johnston\0"
    "James Temple\0"
    "Jarrod Bezzina\0"
    "jedimatt42\0"
    "Jeri Mason\0"
    "Jeroen Vandezande\0"
    "Jérôme Rabas\0"
    "Joakim Ekblad\0"
    "Joe Tom Collins\0"
    "Johan jonsson\0"
    "Johan Smolinski\0"
    "jonathan Wickett\0"
    "June Tate-Gans\0"
    "Kasper Olesen\0"
    "Kolbjørn Barmen\0"
    "Kuba\0"
    "Lemaru\0"
    "Łukasz Ratajczyk\0"
    "M.B.\0"
    "MAARTEN\0"
    "Madgrizzle\0"
    "Mahen\0"
    "Maic Striepe\0"
    "Manuel Montoto\0"
    "Marcin Panawa\0"
    "Marco Rodriguez\0"
    "Marcus Agehall\0"
    "Marcus Bengtsson\0"
    "Marcus Gerards\0"
    "Mark\0"
    "Mark Jaques\0"
    "Marlon Beijer\0"
    "Martin Lukasek\0"
    "maryoosh_k\0"
    "Mateusz Przybylski\0"
    "Mateusz Staniszew\0"
    "Matthew McGee\0"
    "mdpye\0"
    "Michael\0"
    "Michael Jakes\0"
    "Michael Longval\0"
    "Mikes Retro Tech\0"
    "MiloLovesChocolate\0"
    "Miloslav Martinka\0"
    "MV Imaging\0"
    "Nick L\0"
    "Nicklas Berg\0"
    "Niko Tomatsidis\0"
    "Nisse H\0"
    "Paladinprime\0"
    "patracy\0"
    "Paul Atreides\0"
    "Peter Knöll\0"
    "Peter Persson\0"
    "Petter Lindquist\0"
    "prometeusz84\0"
    "Przemysław Stalmach\0"
    "Rastislav Seffer\0"
    "Remigiusz\0"
    "Renaud Schweingruber\0"
    "Renee Cousins\0"
    "renewable_intel\0"
    "Retrofletch\0"
    "RetroPassion Ltd\0"
    "Richard Prokesch\0"
    "Riot Retro Gaming\0"
    "Rob\0"
    "Roberto Meloni\0"
    "Roberto Monticelli\0"
    "Robin Southern\0"
    "RoC\0"
    "RoWi\0"
    "RRenfrow\0"
    "Ruben\0"
    "Samuel Crow\0"
    "Sarmad Gilani\0"
    "Serge Alves\0"
    "shoe\0"
    "Sieur Orage (Allan)\0"
    "Sigurbjorn B. Larusson\0"
    "Simon\0"
    "Simon Lee\0"
    "Simon Osborne\0"
    "SimonV\0"
    "Smarthuman\0"
    "Stefan Blixth\0"
    "Stefan Knoblich\0"
    "Stefan Reinauer\0"
    "Steffen Barabasch\0"
    "Stephane Jacob\0"
    "Stephen Frame\0"
    "Steve Hodson\0"
    "Steve Jones\0"
    "Steven Taylor\0"
    "Surfbud\0"
    "Tamás Vándorffy\0"
    "The Amiga Show\0"
    "The Undertaker\0"
    "Thomas Oeding\0"
    "Thomas Radeck\0"
    "Thomas Scheller\0"
    "Tijnz \0"
    "Timothy Deters\0"
    "Tobias Seiler\0"
    "Todd Chamberlain\0"
    "Tomas Kaluzik\0"
    "Tomek Rymarczuk\0"
    "Tomek Zalega\0"
    "Tonny Roger Holm\0"
    "Torsten Kurbad\0"
    "Vito Leva\0"
    "Vova Stegantsov\0"
    "Webba\0"
    "Wolfgang Schuster\0"
};
const unsigned long supporters_size = sizeof(supporters);

#endif /* _SPONSORING_H */
