#!/bin/bash
if [ ! -v TTY_ENABLED ]; then
	TTY_ENABLED="-it"
fi

docker run --rm ${TTY_ENABLED} -u $(id -u):$(id -g) -v $(dirname "${PWD}"):$(dirname "${PWD}") -w $PWD amigadev/crosstools:m68k-amigaos "$@"
